version: "2"

services:
  app1:
    build: ./python_app/
    hostname: "app1"
    ports:
      - "8080:8080"
    depends_on:
      - consul1


  app2:
    build: ./python_app/
    hostname: "app2"
    ports:
      - "8081:8080"
    depends_on:
      - app1


  consul1:
    image: "consul:latest"
    container_name: "consul1"
    hostname: "consul1"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "53:8600"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

  consul2:
    image: "consul:latest"
    container_name: "consul2"
    hostname: "consul2"
    expose:
      - "8400"
      - "8500"
      - "8600"
    command: "agent -server -join consul1 -client 0.0.0.0"
    depends_on:
      - consul1

  consul3:
    image: "consul:latest"
    container_name: "consul3"
    hostname: "consul3"
    expose:
      - "8400"
      - "8500"
      - "8600"
    command: "agent -server -join consul1 -client 0.0.0.0"
    depends_on:
      - consul1
